# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-29 16:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='external ID')),
                ('account_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_where_owner', to=settings.AUTH_USER_MODEL, verbose_name='account owner')),
                ('account_staff', models.ManyToManyField(related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='account_staff')),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_where_assistant', to=settings.AUTH_USER_MODEL, verbose_name='assistant')),
                ('delivery_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_where_dd', to=settings.AUTH_USER_MODEL, verbose_name='delivery director')),
            ],
            options={
                'verbose_name': 'account',
                'ordering': ['name', 'id'],
                'verbose_name_plural': 'accounts',
            },
        ),
    ]
