# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-29 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
